Upgrade EC2 runners to 2.6.1 to support Node.js 24
Fixes this error:

`Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Run machulav/ec2-github-runner@a6dbcefcf8a31a861f5e078bb153ed332130c512
Error: GitHub Registration Token receiving error
Error: HttpError: Bad credentials - https://docs.github.com/rest
Error: Bad credentials - https://docs.github.com/rest`

because the previous versoin only supports up to Node.js 20

Signed-off-by: Courtney Pacheco <6019922+courtneypacheco@users.noreply.github.com>